APIサーバーからUUIDを取得
YosukeSasaoka/tba-app-client pull request #19
Opened 2017-01-04 01:43 UTC by MitsuhiroKamei

#16 の対応です。

下記の記事とサンプルコードをだいぶ参考に(真似)しました。
http://blog.bokuweb.me/entry/redux-tutorial
https://github.com/bokuweb/react-tutorial-with-redux

□注意点
・元のToDoサンプルはごっそり削除しています。
・URIを直書きしていますので、まだ実用的ではないと思います。
・動作を確認する際には、クロスドメインの制約を回避する必要があります。(対応例 http://traincat.net/blog/neko/archives/000414.html)

2017-01-04 01:53 UTC, YosukeSasaoka commented
@MitsuhiroKamei 

PRありがとうございます。
確認しておきます。

2017-01-05 12:31 UTC, YosukeSasaoka commented
@MitsuhiroKamei 

僕の方はレビューしてOKです。
多田さんにレビューして貰って問題ないようでしたらmergeしておきます。

2017-01-06 05:41 UTC, k-tada requested changes

2017-01-06 05:41 UTC, k-tada commented on src/js/store/configureStore.js
> +  const store = createStoreWithMiddleware(uuid);
uuidのReducerを直に渡すのではなく、例えば`src/js/reducers/index.js`などで他のReducerもっまとめたものをstoreに渡してください。Reducerをまとめるのは`combineReducers`を使用すればOKです。

2017-01-06 05:41 UTC, k-tada commented on src/js/reducers/uuid.js
> +     return {uuid : action.uuid};
combineReducersでReducerをまとめた際に、`state.<reducer name>`という形で各reducerにアクセスすることになります。
その場合、この形でstateを持つと、uuidの実体へのアクセスが`state.uuid.uuid`になってしまうので、このreducerでのuuidの持ち方はObjectではなくStringの方がいいかもです。
uuidに今後他のパラメータを追加する場合はObjectでもOKですが、その場合は名称を変更したほうがいいかと。

2017-01-06 05:41 UTC, k-tada commented
@MitsuhiroKamei レビューしました。ご確認お願いします。

2017-01-07 06:34 UTC, MitsuhiroKamei commented
@k-tada
レビューありがとうございます。修正しました。
ご指摘の通りに修正できているかどうか、
再度レビューして頂ければと思います。

2017-01-09 00:44 UTC, YosukeSasaoka commented on src/js/app.js
> +)
@MitsuhiroKamei 

ルーティングの設定を容易にしてくれるので、react-routerを使用した方が良いと思います。
指摘が遅くなってすみません。

2017-01-09 09:40 UTC, MitsuhiroKamei commented on src/js/app.js
> +)
@YosukeSasaoka

承知しました。
いきなりreact-routerとreduxの併存は、
ハードルが高いかなと思ったので、後回しにしていました。
※まさにこの"ReactDOM.render()"の中をどう書けば良いのかではまりそうな気がしました。
とりあえずreduxを使用して動くものが実装できたので、
react-routerも使うように変更していきます。

2017-01-11 02:11 UTC, YosukeSasaoka commented on src/js/app.js
> +)
@MitsuhiroKamei 

承知しました。

react-routerとreduxの併存させるために↓のプラグインを入れた方が実装がし易いのかなと思いました。ご参考までに。
` redux-router `

GitHub
https://github.com/acdlite/redux-router

参考サイト
http://tnakamura.hatenablog.com/entry/2015/12/14/091648

2017-01-17 03:40 UTC, k-tada commented on src/js/app.js
> +)
@MitsuhiroKamei 
Redux + Router周りのライブラリに関しては、現状どれがベストかっていうのは未だ議論の最中にあるようで、「これがいい」とは一概に言えないようです。（むしろ現状「どれもダメだ」ってなってて、だけど誰もベストな実装をなし得てないという状況に近い）

私は別のプロジェクトでは`react-router-redux`を使っていますが、`redux-router`や他のライブラリも選択肢としてはアリなんじゃないかと。
ちなみに私が`react-router-redux`を選択した理由は単純にスターが多かったためです。

2017-01-17 03:47 UTC, k-tada requested changes

2017-01-17 03:47 UTC, k-tada commented on src/js/reducers/index.js
> +export default uuidApp
combineReducersの使い方はこれでOKです！
ただ`combineReducersを使う`＝`uuid以外のreducerも含めて全てのreducerを統括`ということなので、uuidAppという名前が微妙かなと思いました。
単純に `export default combineReducers(〜)`でいいのではないでしょうか。

2017-01-17 03:58 UTC, k-tada commented on src/js/reducers/index.js
> +export default uuidApp
あ、もういっこのPRのほうで直ってたんですね。失礼しました。

2017-01-17 04:45 UTC, k-tada commented on src/js/app.js
> +)
http://www.npmtrends.com/react-router-redux-vs-redux-router
結構差がついてた

2017-01-18 12:09 UTC, merged